# Generated by Django 4.0.6 on 2022-09-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_title_anuncio_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='titulo',
            new_name='autor',
        ),
    ]
