# Generated by Django 4.0.6 on 2022-10-14 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSv', models.CharField(max_length=200)),
                ('descSv', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
